### ISSUE TITLE
Trying to conditionally ignore property on deserialization but SetShouldSerializeMethod not working for mapped member

### ISSUE THREAD

**Issue by JimCline** [dahomey-technologies/Dahomey.Json#102]
I need to conditionally ignore a property during deserialization and I thought the SetShouldSerializeMethod would work for both serialization and deserialization but it doesn't seem to.

Is there a way to conditionally ignore a property during deserialization?

**Comment by mcatanzariti** [comment]
ShouldSerializeMethod is supported only for serialization not deserialization like in Json.net or XmlSerializer
