### ISSUE TITLE
Deserialize strings into ReadOnlyMemory<char>

### ISSUE THREAD

**Issue by vova-lantsov-dev** [dahomey-technologies/Dahomey.Json#11]
What do you think, is it possible to write as following:

```c#
public class MyModel
{
  public ReadOnlyMemory<char> Name { get; set; }
}
```
For
```
{
  "Name": "John"
}
```
And is it reasonable?

**Comment by mcatanzariti** [comment]
cf. https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/Issues/Issue0011.cs
