### ISSUE TITLE
InvalidCastException when serializing object property

### ISSUE THREAD

**Issue by 0x084E** [dahomey-technologies/Dahomey.Json#19]
If I try to deserialize the following type, I get an invalid cast exception because the resolved JsonConverterString doesn't implement IObjectConverter.

``` C#
public class Test
{
    public object Property { get; set; } = "Test";
}
```

**Comment by mcatanzariti** [comment]
@0x084E, if you want to help, I need more information:

- JSON to deserialize
- Code sample
- Exception callstack

Thank you!

**Comment by mcatanzariti** [comment]
I finally reproduced it: the exception occurs when serializing the Test class, not deserializing it.
