### ISSUE TITLE
Read from File with multiple derived classes

### ISSUE THREAD

**Issue by DeckardCain2014** [dahomey-technologies/Dahomey.Json#21]
Hi,

I'm using your library primarily for supporting serialization and deserialization of polymorphic objects. I have a base class "DataSetBase" and two deriving classes, "DataSet" and "BlackoutDataSet". 
Following the serialization:
```
JsonSerializerOptions options = new JsonSerializerOptions().SetupExtensions();
DiscriminatorConventionRegistry registry = options.GetDiscriminatorConventionRegistry();
registry.RegisterType<DataSet>();
registry.RegisterType<BlackoutDataSet>();

using (var fileWriter = new StreamWriter(_failureFolderPath + GetFailureFileName(), true)){
	if (dataSet is DataSet)
	{
		jsonString = JsonSerializer.Serialize<DataSetBase>((DataSet)dataSet, options);
	}
	else if (dataSet is BlackoutDataSet)
	{
		jsonString = JsonSerializer.Serialize<DataSetBase>((BlackoutDataSet)dataSet, options);
	}
	else
	{
		throw Exception("Got unknown type");
	}

	if (jsonString != "")
		fileWriter.WriteLine(jsonString);
}
```

How can I be sure of the type of the object when deserializing?
```
ReadOnlySpan<byte> jsonReadOnlySpan = File.ReadAllBytes(_failureFolderPath + GetFailureFileName());
var reader = new Utf8JsonReader(jsonReadOnlySpan);
while (reader.Read()){
	var deserializedObject = JsonSerializer.Deserialize<????>(reader, options);
}
```

**Comment by mcatanzariti** [comment]
Hi,

First you can directly serialize/deserialize from a stream

You should just deserialize using base type and the framework will instantiate an inherited type based on the discriminator read from the json stream

```csharp
using (FileStream stream = File.OpenRead(_failureFolderPath + GetFailureFileName())
{
    var deserializedObject = JsonSerializer.Deserialize<BlackoutDataSet>(stream, options);
}
```

**Comment by DeckardCain2014** [comment]
Okay, thanks. I will try that!

**Comment by mcatanzariti** [comment]
Don't forget to setup a discriminator on each inherited class. You can decorate the class with JsonDiscriminatorAttribute or use ObjectMapping<T>.SetDiscriminator method.

Then you have to register your class in the discriminator registry.

For further details, see
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/README.md#polymorphism

Don't hesitate to reopen if you have any problem.

**Comment by DeckardCain2014** [comment]
Is the following code sufficient?
``` 
JsonSerializerOptions options = new JsonSerializerOptions().SetupExtensions();
DiscriminatorConventionRegistry registry = options.GetDiscriminatorConventionRegistry();
registry.RegisterType<DtoOpcDataSet>();
registry.RegisterType<DtoOpcBlackoutDataSet>();
```

**Comment by mcatanzariti** [comment]
You should also decorate OpcBlackoutDataSet with JsonDiscriminatorAttribute. Please see README.md for further details.

**Comment by DeckardCain2014** [comment]
Hi, 
thanks for getting back to me. However, when using
` registry.RegisterConvention(new DefaultDiscriminatorConvention<int>(options, "_t")); ` it throws me an error "DefaultDiscriminatorConvention is non generic type".

**Comment by mcatanzariti** [comment]
@DeckardCain2014 Be sure to use last version published on nuget (1.6.0)

**Comment by DeckardCain2014** [comment]
Hi @mcatanzariti ,

sorry for calling back. I tried the latest version. It is serializing correctly (see my sample file attached).[Simulator-Xx_FailureFile.zip](https://github.com/dahomey-technologies/Dahomey.Json/files/4101451/Simulator-Xx_FailureFile.zip)

However, when deserializing with the same registered types, it throws a "System.Text.Json.JsonException".
![Deserializing](https://user-images.githubusercontent.com/10652393/72960166-15a51b80-3dad-11ea-83d7-07f6a819f283.png)
![Exception](https://user-images.githubusercontent.com/10652393/72960169-176edf00-3dad-11ea-85c9-38ba01f3bbfc.png)

**Comment by mcatanzariti** [comment]
@DeckardCain2014 It seems that you are trying to implement a"new line delimited json" processor.
You won't be able to deserialize this kind of format directly with System.Text.Json.

So you should read the file line by line with a StreamReader or a PipeReader (more performant) and deserialize each line separately with the JsonSerializer class.

**Comment by DeckardCain2014** [comment]
You gave me the code sample before closing this issue, so I thought it might be the best possibility to deserialize the file. Can you give me an example how to use the Stream or Pipe Reader? Is it possible to use the new Utf8JsonReader?

**Comment by mcatanzariti** [comment]
I gave you a code sample for a well formatted json file.
The format I can see in your zip file is not compliant with the json specification.
But it seems to be compliant with the new line delimited json format used for streaming json.

In other words, a collection of object expressed in strict json would be:
[{...},{...},{...}]

A collection expressed in newline delimited json would be
{...}\n{...}\n{...}

First you have to decide which format you target.
Second you should be aware that neither System.Text.Json nor Dahomey.Json support newline delimited json.

If you want to target strict json, just use JsonSerializer.Serialize and JsonSerializer.Deserialize directly with a FileStream and a C# List<T>

If you want to target newline delimited json, you should read and write lines one by one with a StreamReader / StreamWriter. In this case line will be expressed via a C# string and you will be able to use JsonSerializer.Serialize and JsonSerializer.Deserialize based on a string and an item of a List<>. It means you will have to iterate the list items when writing and to insert the list item manually to the list when reading.

Whatever the option you choose, you should not use Utf8JsonReader/Writer directly

**Comment by DeckardCain2014** [comment]
StreamReader was the solution. Thanks!
