### ISSUE TITLE
Regression for the DataMemberAttribute support

### ISSUE THREAD

**Issue by NSentinel** [dahomey-technologies/Dahomey.Json#24]
Version `1.6.0` (at least, upgraded from `1.1.4`) ignores `DataMemberAttribute`

Test:

```csharp
        public class MemberNameSerialization
        {
            [DataMember(Name = "memberName")]
            public int A { get; set; } = 1;
        }
```

```csharp
        [Fact]
        public void MemberNameSerializationTest()
        {
            var jsonSerialized = JsonSerializer.Serialize(new MemberNameSerialization(), new JsonSerializerOptions().SetupExtensions());
            Assert.Contains("memberName", jsonSerialized);
        }
```

Expected:

```json
{
  "memberName": 1
}
```

Actual:

```json
{
   "A":1
}
```

**Comment by mcatanzariti** [comment]
Hi @NSentinel, you need to decorate your class with [DataContract] attribute.

**Comment by NSentinel** [comment]
Hi @mcatanzariti, this is very sad since I wanted to avoid changing around 1000 DTOs. That's why I ask you for the first time. 

This change is similar to moving to the new `JsonProperty` since it is no longer possible to simply use the existing library code as with `Utf8Json` or `Jil` or with the version in your initial implementation.

We never specifically marked with the `[DataContract]` attribute, as the serializer did not require this. And even having completed the markup on the current code base, we will have to do some additional verification for new code, since the team does not have the necessary habits.

Ok, since you closed the ticket, apparently I should do it myself as it suits our purposes.

In any case, thanks for your work!

**Comment by mcatanzariti** [comment]
Hi @NSentinel 

If you to avoid marking all your classes, you can write your own mapping convention provider adapted from StandardObjectMappingConventionProvider:

```csharp
public class CustomObjectMappingConventionProvider : IObjectMappingConventionProvider
{
    private static readonly StandardObjectMappingConvention _standardObjectMappingConvention = new StandardObjectMappingConvention();

    public IObjectMappingConvention? GetConvention(Type type)
    {
        return _standardObjectMappingConvention;
    }
}
```

Then register it in your serialization options:

```csharp
JsonSerializerOptions options = new JsonSerializerOptions();
options.SetupExtensions();
options.GetObjectMappingConventionRegistry().RegisterProvider(
    new CustomObjectMappingConventionProvider()
);
```

To give simple explanation, an object mapping convention purpose is a strategy to map classes with serialization options.

The standard convention is based on C# common serialization attributes like DataMember and the default one is based on Dahomey specific attributes.

Then a provider must be created to let know the framework on which type to apply the convention.

The standard provider apply it only for types decorated with DataContractAttribute.

In your case, you want all the classes to be associated with the standard convention. Consequently, you can create a new provider that will return the standard convention without any condition.

Hope it will help you.

**Comment by NSentinel** [comment]
Hello @mcatanzariti

Thank you for your answer!

Yesterday I found your discussion about these changes, the required interface, and implementation in the source code. In the end, I really took advantage of the new mechanism (`IMappingObjectConventionProvider`) to solve my issues.  To do this, I combined the implementations of `Default` and `Standard` providers, as it was necessary to ensure the combined work for both attributes.

The only thing I miss is the ability to clear the list of providers in order to place my provider last on the list (as an alternative to current `Default`), so I just added duplicate for standard providers so as not to break ordinary behavior in cases when it worked fine.

I understand that you have made it possible to filter provider by type so that you can enable the provider if necessary, but I can't make any specific rule for our codebase to use this (many of DTOs are structs), therefore I implemented the merged `Default` behavior that takes both attributes into account.

Is there an easier way to implement it?

**Comment by mcatanzariti** [comment]
@NSentinel actually the last added provider will be called first. It means your provider will be called first, then the standard one, and finally the default one. If you return null in your provider, the framework will fallback to the standard and default providers
So I don't see the need to clear providers...

Concerning the possibility to merge several providers features, I can't see any simple solution with the current implementation of the framework.

I don't understand why struct DTOs are more problematic than class DTOs.

Nevertheless, if you explain me deeper which feature of each provider you need to merge, I could maybe find a solution.

**Comment by NSentinel** [comment]
I have read in the source code that `ConcurrentStack` is used and my provider will be the first after adding. The issue is that you either have to include the behavior of all the other implemented ones (for example, `AnonymousObjectMappingConventionProvider`) or skip processing for some types in some way (return `null`) so the regular behavior works, which requires a way to determine these types, which is difficult in our case.

A few details about our project. A lot of different serializers have been historically used in our project: https://www.newtonsoft.com/json (almost everywhere removed), https://github.com/kevin-montrose/Jil, https://github.com/neuecc/Utf8json

In the transition to .NET Core, we decided to normalize projects and unify JSON serializers by choosing the standard offered by Microsoft, which is now also working with acceptable performance.

As a result, we are faced with the fact that there are a lot of restrictions in the current version of `JsonSerializer`:

- bad (no) support for structs and fields;
- no support for `DataMemberAttribute`;
- our usage for Jil-specific attributes (now migrated);
- our specific requirements for serializing `DateTime` (wrote required converters) and etc.

With the help of your library, we managed to close blockers (support for fields for example) (thanks!).

For structures and classes where the `DataMemberAttribute` was explicitly defined and the source code is available, we duplicated (by using a custom utility) `JsonProperty` attributes. Duplication (instead of replacement) is caused by the fact that some projects cannot be switched to .NET Core and it is required that they can also be serialized by using old versions.

Two issues remain unresolved:

- there are libraries for which we do not have source code and where `DataMember` attribute is used (technically, they can be decompiled and reassembled, but this is not a good solution). They also have no `DataContract` attribute specified.

- not the whole team got used to the need to write `JsonProperty` instead of `DataMember`. Yes, we can check (review) or automatically run the utility within the CI pipeline, but an automatic modification of the source texts within the build is also not a good practice.

As a result, the optimal intermediate solution was to allow support for `DataMemberAttribute` and gradually migrate the entire project. This mode, by the way, was supported by both `Jil`(when we switched from `JSON.NET`) and `Utf8Json` (when we switched from `Jil` and the part remained with the old markup).

**Comment by mcatanzariti** [comment]
@NSentinel thanks for the detailed explanation!

If I understand well, you have to support classes/structs decorated with DataContractAttribute and other classes/structs with JsonPropertyAttribute. But you won't have classes/structs with mixed attributes.

So you could setup your provider in this way:

```csharp
public class CustomObjectMappingConventionProvider : IObjectMappingConventionProvider
{
    private static readonly StandardObjectMappingConvention _standardObjectMappingConvention = new StandardObjectMappingConvention();

    public IObjectMappingConvention? GetConvention(Type type)
    {
        if (type.GetProperties().Any(p => p.IsDefined(typeof(DataMemberAttribute))))
        {
            return _standardObjectMappingConvention;
        }

        return null;
    }
}
```
If type holds at least one property decorated with DataMemberAttribute, then it will be mapped by the standard convention. If not, the framework will fallback to the default convention.

Hope it helps

**Comment by NSentinel** [comment]
@mcatanzariti Thanks for the idea, I thought about it, but was concerned about the performance of the reflection (checking attributes of both properties and fields is required. It is approximate ~150 μs additional cost per call on a test set of type/fields). But I think this option will still be better than my original, as it integrates more naturally with your library.

As a result, at the moment, I have taken your version as a basis by adding simple caching results by type.

Thank you for the help!

**Comment by mcatanzariti** [comment]
Hi @NSentinel,

I can understand your concern about performance, but I would like to make sure you are aware that the mapping process happen only once per type.

The whole library design is based on the fact that once a type is mapped, all the subsequent serializations/deserializations for this type won't call any reflection code. Indeed, each requested information concerning the type and its members are cached in a JsonConverter.

Moreover, I'm thinking on a solution to avoid the dictionary lookup on the JsonConverter when requesting it via the generic GetConverter<T> method.

Hope it helps

**Comment by NSentinel** [comment]
Hi @mcatanzariti,

I somehow missed the `Lookup` method while reading the source code. Thank you for drawing my attention! I will remove caching on my side.

Looking forward to new updates. Thank you for your work!
