### ISSUE TITLE
Allow registering discriminators without having to decorate a class.

### ISSUE THREAD

**Issue by CheloXL** [dahomey-technologies/Dahomey.Json#26]
I have the need to use discriminators on sealed classes that I don't own. It would be nice if I could simply set the discriminator value in the RegisterType method instead of using an attribute (like `registry.RegisterType<RemotingRequest>("remoting-request");`).

**Comment by mcatanzariti** [comment]
Hi,

It's already supported:

```csharp
options.GetObjectMappingRegistry().Register<RemotingRequest>(objectMapping =>
                objectMapping
                    .AutoMap()
                    .SetDiscriminator("remoting-request");
```

**Comment by CheloXL** [comment]
Ahh... documentation for that would be great!

**Comment by rafaelbenavent** [comment]
Can we get a small example on using this feature? I'm trying to use it to (de)serialize an interface/abstract class and it is not working.

**Comment by mcatanzariti** [comment]
Sorry for the lack of documentation.

You will find an exemple here (method ReadWithDiscriminator):
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/ObjectMappingTests.cs

Let me know if it covers your requirements

**Comment by rafaelbenavent** [comment]
Thank you! The tests are a good source of documentation. :)

**Comment by rafaelbenavent** [comment]
@mcatanzariti is it possible to register by type, and not by generic?

**Comment by mcatanzariti** [comment]
@rafaelbenavent not currently. The class ObjectMapping<> is a generic and it would a huge refactoring not to use it

**Comment by rafaelbenavent** [comment]
What about making a non-generic ObjectMapping that would live side by side the generic one?

**Comment by mcatanzariti** [comment]
@rafaelbenavent please check my answer here:
https://github.com/dahomey-technologies/Dahomey.Json/issues/39
