### ISSUE TITLE
Question: Is the DefaultValue mandatory?

### ISSUE THREAD

**Issue by raRaRa** [dahomey-technologies/Dahomey.Json#37]
Just a quick question. Is it mandatory to use the `DefaultValue` attribute for boolean variables that should be ignored when they are false? Shouldn't a boolean variable that is false be ignored by default?

Thanks.

**Comment by raRaRa** [comment]
I just tried it out and I can confirm that I need to explicitly add it for boolean values. It would be really neat if there was a way to configure `SetupExtension` to ignore default value without having to specify `[JsonIgnoreIfDefault]`

**Comment by mcatanzariti** [comment]
@raRaRa I may add an option to ignore default values as a global option but it would not be specifically for booleans but for all types

**Comment by raRaRa** [comment]
Sounds good, thanks!
