### ISSUE TITLE
Exception when using DefaultValue on uint

### ISSUE THREAD

**Issue by raRaRa** [dahomey-technologies/Dahomey.Json#38]
I'm getting an exception when I try to serialize an object that has something like:

```
[JsonPropertyName("marginBottom"), DefaultValue(45)]
public uint MarginBottom { get; set; }
```

It will throw a `Default value type mismatch`. The issue is that it thinks that 45 is an int, and int != uint.

I had the same issue for double, but I fixed it by adding a coma to the number in the `DefaultValue`, e.g. `DefaultValue(6.0)`

**Comment by mcatanzariti** [comment]
@raRaRa You have to options:
```csharp
[JsonPropertyName("marginBottom"), DefaultValue((uint)45)]
public uint MarginBottom { get; set; }
```
or 
```csharp
[JsonPropertyName("marginBottom"), DefaultValue(45u)]
public uint MarginBottom { get; set; }
```
cf. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#integer-literals
