### ISSUE TITLE
Register by type

### ISSUE THREAD

**Issue by rafaelbenavent** [dahomey-technologies/Dahomey.Json#39]
Currently there's a generic method for registering a type, but a Register(Type type...) version would be nice as well.

**Comment by mcatanzariti** [comment]
@rafaelbenavent Please describe your exact use case, I may have a solution for you with ObjectMappingConventionProvider and ObjectMappingConvention. This 2 class allow to define a common object mapping strategy for several types

**Comment by rafaelbenavent** [comment]
@mcatanzariti I'd like to register all types in a given assembly that match certain criteria. Something like this:

`
// pseudo code
foreach (var type in myAssembly,GetTypes().Where(someCondition))
   // Register type
 options.GetObjectMappingRegistry().Register(type, objectMapping =>
                objectMapping
                    .AutoMap()
                    .SetDiscriminator(type.Name)

`

**Comment by mcatanzariti** [comment]
@rafaelbenavent I have good news for you! It's already doeable with an object mapping convention.

You will find an example here:
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/ObjectMappingTests.cs method OptIn.

Let me know if you need a concrete example with your use case

**Comment by rafaelbenavent** [comment]
@mcatanzariti that would be great. I've been having a hard time getting it to work. Here's my code trying to only register OptIn1 and not register OptIn2.

```
       public class OptInObjectMappingConventionProvider : IObjectMappingConventionProvider
        {
            public IObjectMappingConvention GetConvention(Type type)
            {
                // here you could filter which type should be optIn and return null for other types
                return type == typeof(OptInObject1) ? new DefaultObjectMappingConvention() :
                    null;
            }
        }
        public class OptInObject1
        {
            public int Id { get; set; }

            public string Name { get; set; }
        }

        public class OptInObject2
        {
            public int Id { get; set; }

            public string Name { get; set; }
        }

        [Fact]
        public void OptIn()
        {
            var options = new JsonSerializerOptions().SetupExtensions();
            options.GetDiscriminatorConventionRegistry().ClearConventions();
            options.GetObjectMappingConventionRegistry().RegisterProvider(
                new OptInObjectMappingConventionProvider()
            );
            var json = JsonSerializer.Serialize(new OptInObject1{Id = 333, Name = "ddd"}, options);
            var obj = JsonSerializer.Deserialize(json, typeof(OptInObject1), options);

            var json2 = JsonSerializer.Serialize(new OptInObject1 { Id = 344433, Name = "dddsdsd" }, options);
            var obj2 = JsonSerializer.Deserialize(json2, typeof(OptInObject2), options);
        }

**Comment by mcatanzariti** [comment]
You will find an example with your use case here:
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/Issues/Issue0039.cs
