### ISSUE TITLE
Error serializing entity with IReadOnlyCollection<> 

### ISSUE THREAD

**Issue by CheloXL** [dahomey-technologies/Dahomey.Json#4]
I have a class that's defined as following:

```cs
public sealed class SignedDocument
{
	public SignedDocument([NotNull] string id, [NotNull] string name, IReadOnlyCollection<SignatureDefinition> signatureDefinitions)
	{
		Id = id;
		Name = name;
		SignatureDefinitions = signatureDefinitions;
	}

	public string Id { get; }
	public string Name { get; }
	public IReadOnlyCollection<SignatureDefinition> SignatureDefinitions { get; }
}
```
When I try to serialize it, I get the following error: 'System.InvalidCastException: 'Unable to cast object of type 'Dahomey.Json.Serialization.Converters.ArrayConverter`1[DDS.DigitalSigner.Domain.ValueObjects.SignatureDefinition]' to type 'Dahomey.Json.Serialization.Converters.IObjectConverter'.'`

If I change the IReadOnlyCollection by an array (for example) everything works.

**Comment by vova-lantsov-dev** [comment]
@CheloXL I took a look at this problem, it's because all collection-related converters don't implement the IObjectConverter interface as well as dictionary-related converters. I tried to realize how to fix it, but have no idea.

**Comment by mcatanzariti** [comment]
@vova-lantsov-dev collections converters are not supposed to implement IObjectConverter.

The issue is linked to the fact that IReadOnlyCollection is not handled CollectionConverterFactory and the type selection process falls back to ObjectConverterFactory.
