### ISSUE TITLE
Support explicit (or at least deterministic) ordering of serialized json

### ISSUE THREAD

**Issue by bjorhn** [dahomey-technologies/Dahomey.Json#50]
Would it be possible for this library to support explicit ordering of serialized json? Perhaps with some kind of Order attribute, or by having an option to always serialize in the same order that properties are defined in classes (i.e. top-to-bottom)?

It doesn't look like System.Text.Json will support it in the near future, and this library seems like a suitable place to implement such a feature.

**Comment by mcatanzariti** [comment]
@bjorhn the serialization order is meant to be deterministic based on class definition.
Do you have an issue with this feature?

**Comment by bjorhn** [comment]
Yeah, I do! According to Microsoft it isn't mean to be determinsitic at all, because "JSON is generally unordered (i.e. folks shouldn't be relying on the ordering of the properties within the payload)". It seems to be based on the order of which properties were get/set, I don't recall exactly how it works, but order is not written according to how the properties are listed in the classes.

See the following issue: https://github.com/dotnet/runtime/issues/728

**Comment by mcatanzariti** [comment]
My point is that in Dahomey.Json (not in the genuine System.Text.Json library), json properties are meant to be ordered following the class declaration.

If it is not the case, please provide a sample that reproduces the issue.

**Comment by bjorhn** [comment]
That's interesting, I wasn't aware of that. Give me a couple of days and I'll put together some sort of minimal sample project that illustrates the issue.

**Comment by mcatanzariti** [comment]
@bjorhn any repro?

**Comment by bjorhn** [comment]
Not yet! Got distracted with holidays for a while but now that I'm back at work we're noticing it more regularly again.

Everything seems consistent whenever we sit down and try to reproduce the issue. So we move on to other tasks, and eventually we do something that appears to trigger properties all over the data structure to get re-ordered. We're now keeping closer track of when this happens, so we can try to go back a commit or two to see if we can reproduce the problem in a repeatable manner.

**Comment by bjorhn** [comment]
I'd like to apologize for not getting back to this issue sooner. I spend an hour every couple of weeks trying to create a minimal sample project that reproduces the error, but so far I've been unable to do so. Meanwhile, the issue keeps happening regularly when using the application I've created that uses System.Text.Json + Dahomey.Json.

Let me show you an example of how the problem manifests itself.

This first image shows how the public properties of one of my serializable classes are defined:
![source](https://user-images.githubusercontent.com/421316/93493339-170eef80-f90c-11ea-936d-3599d72421e3.png)

Let's focus on the order of the three public properties visible in the image: ExtendedProperties, LoadColumn, Satellite.

After using my application to serialize the object structure to a json file, Github displayed the following diff when I was preparing my PR:
![github diff](https://user-images.githubusercontent.com/421316/93493469-39a10880-f90c-11ea-8783-83adb7efaa98.png)

Our three properties of interest have been serialized in the follow order: LoadColumn, Satellite, ExtendedProperties. This differs from the order in which they are defined within the class.

About an hour later I was using my application to edit a property (something minor, I changed an integer value somewhere), and after re-serializing the structure to the json file again, VS Code displayed the following diff:
![second diff, after saving again](https://user-images.githubusercontent.com/421316/93493589-59383100-f90c-11ea-9042-75f44fe5d234.png)

The three properties are now in the following order: LoadColumn, ExtendedProperties and Satellite. For some reason, ExtendedProperties and Satellite have swapped orders, despite no code changes being made my application.

It's not always these two properties that swap places, sometimes it's other properties like Scale and Nullable.

Do you have any idea of what might be causing this? Is it a bug in the library, or a user error on my part?

I'm using .NET 5.0 Preview 7 and when these pictures were taken I was using Dahomey.Json 1.9.0

**Comment by mcatanzariti** [comment]
Hi @bjorhn,

Could you provide the whole definition of the StagingColumn class, please?
I'm relying on Type.GetProperties order to serialize.
Could the .Net framework not respect the declaration order whne exposing properties with the GetProperties method?

**Comment by bjorhn** [comment]
Of course, I've attached the class definition file (had to change it to .txt). Let me know if you need anything else, like base classes or other files. The code is a bit of a mess, it's not meant to be public yet.. :)

I don't know much about how Type.GetProperties works. I wonder if I could print the contents of Type.GetProperties to a file every time I re-save my metadata structure? Like I mentioned before the order doesn't change every time, but that way I would have the printed output saved to disk when it does happen, and we could follow up on whether the order changes.

[StagingColumn.txt](https://github.com/dahomey-technologies/Dahomey.Json/files/5247603/StagingColumn.txt)

**Comment by mcatanzariti** [comment]
Hi @bjorhn,

I cannot explain why the order would change. Are you sure to use Dahomey.Json by calling the extension method SetupExtensions()?

As a workaround, you could map manually your properties in Dahomey.Json. Then you class will be serialized by following the order of declaration in the manual mapping:

```csharp
var options = new JsonSerializerOptions().SetupExtensions();
options.GetObjectMappingRegistry().Register<StagingColumn>(objectMapping =>
{
    objectMapping
        .AutoMap()
        .ClearMemberMappings();
    objectMapping.MapMember(o => o.Logic);
    objectMapping.MapMember(o => o.ExtendedProperties);
    objectMapping.MapMember(o => o.LoadColumn);
    objectMapping.MapMember(o => o.Satellite);
    objectMapping.MapMember(o => o.Driving);
    // etc.
});
```

Beware not to forget any property otherwise it will be simply ignored during serialization/deserialization.

Hope it helps!

**Comment by bjorhn** [comment]
Hey @mcatanzariti,

I'm pretty sure I'm using Dahomey.json correctly, or am I missing something?
![Screenshot 2020-09-21 002621](https://user-images.githubusercontent.com/421316/93723706-31adc680-fba1-11ea-99ad-a51c9fb7e146.png)

I'm afraid manually mapping the properties would be too much work, but I'll try to figure out some other workaround.

Thanks.
