### ISSUE TITLE
Thank you for this...

### ISSUE THREAD

**Issue by ritchiecarroll** [dahomey-technologies/Dahomey.Json#60]
Switching over from `BinaryFormatter` now that this is deprecated in .NET 5.0, following suggestions to switch to ` System.Text.Json` - everything breaks with derived types, makes me want to swallow razor blades.

Your stuff worked like a charm. You have divinity status.

**Comment by mcatanzariti** [comment]
I have no words but I take the compliments!
🙏🙏🙏🙏
