### ISSUE TITLE
Discriminator not working when it isn't the first property in the json

### ISSUE THREAD

**Issue by NecatiMeral** [dahomey-technologies/Dahomey.Json#62]
Hi, 

thanks for your great library. After hours of trying to use it, I've found out that my issue is the discriminator not being the first property in the json I'm receiving.

I've created a sample test (based on your test cases):
```csharp
        public void ReadPolymorphicObjectWithDeferredTypeProperty()
        {
            const string json = @"{""BaseObject"":{""Name"":""foo"",""Id"":1,""$type"":12}}";

            JsonSerializerOptions options = new JsonSerializerOptions();
            options.SetupExtensions();
            DiscriminatorConventionRegistry registry = options.GetDiscriminatorConventionRegistry();
            registry.ClearConventions();
            registry.RegisterConvention(new DefaultDiscriminatorConvention<int>(options));
            registry.RegisterType<NameObject>();

            BaseObjectHolder obj = JsonSerializer.Deserialize<BaseObjectHolder>(json, options);

            Assert.NotNull(obj);
            Assert.IsType<NameObject>(obj.BaseObject);
            Assert.Equal("foo", ((NameObject)obj.BaseObject).Name);
            Assert.Equal(1, obj.BaseObject.Id);
        }
```

Unfortunately I'm not able to change the property order since I'm not owning the endpoint I'm trying to use.

**Comment by johnhamm** [comment]
*sigh* I am also having this issue as well after hours of struggling with this.  Is there an option to change this?

**Comment by johnhamm** [comment]
https://github.com/jacobdufault/fullserializer places the discriminator as the last property, with no way to change it, while Dahomey.Json places the discriminator as the first property, with no way to change it.  This makes them incompatible.
