### ISSUE TITLE
Need help in one logic conversion

### ISSUE THREAD

**Issue by KamranShahid** [dahomey-technologies/Dahomey.Json#64]
Hi Dahomey,
Can you help me out in following post
https://stackoverflow.com/questions/64729381/defaultcontractresolver-equivalent-in-system-text-json

**Comment by mcatanzariti** [comment]
Please, find an example here: 
https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json.Tests/Issues/Issue0064.cs
