### ISSUE TITLE
Deep nested Polymorphism

### ISSUE THREAD

**Issue by tuath** [dahomey-technologies/Dahomey.Json#70]
Hello, 

If my class to serialize contains a List<Action>, 
The JSON doesn't have a $type for ActionCall, ActionEmail, ActionText...

It seems that $type only shows up on the root node.

**Comment by mcatanzariti** [comment]
Hi @tuath,

Please provide a complete sample with the actual and expected json.

Thank you!

**Comment by mcatanzariti** [comment]
Please, feel free to reopen this issue while you will have provide a sample
