### ISSUE TITLE
Add reference loop handling

### ISSUE THREAD

**Issue by 0x084E** [dahomey-technologies/Dahomey.Json#8]
Even though reference loop handling is scheduled for .NET 5.0 (https://github.com/dotnet/corefx/issues/41002) it would be nice if this could be added in some way. At least an option to ignore them would be really helpful.

**Comment by Jozkee** [comment]
The preview version for `ReferenceHandling` feature is here.

* Download the `System.Text.Json` preview package version `5.0.0-alpha.1.20071.1` from dotnet5 gallery (through Visual Studio's NuGet client):
https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json

* How to use it:
Set `ReferenceHandling.Preserve` to `ReferenceHandling` property in `JsonSerializerOptions`.
```cs
var options = new JsonSerializerOptions
{
    ReferenceHandling = ReferenceHandling.Preserve
};

string json = JsonSerializer.Serialize(objectWithLoops, options);
```
Here's the [spec doc](https://github.com/dotnet/runtime/blob/c23959daba1ccc0f27d74deecf486625304cde7e/src/libraries/System.Text.Json/docs/ReferenceHandling_spec.md) including samples and notes about many scenarios.
If you want to add feedback, feel free to leave a comment in https://github.com/dotnet/corefx/issues/41002.
