### ISSUE TITLE
Same discriminator value for different object hierarchies 

### ISSUE THREAD

**Issue by NikiforovAll** [dahomey-technologies/Dahomey.Json#81]
I would like to use the same discriminator value for different object hierarchies to use the same discriminator value.

I'm not what I need to implement to make it work. Could you please assist?

Currently, I encounter exception at line: <https://github.com/dahomey-technologies/Dahomey.Json/blob/master/src/Dahomey.Json/Serialization/Conventions/DefaultDiscriminatorConvention.cs#L43>

I need something like the following: 

```csharp
public class Base1
{
}

[JsonDiscriminator("Derived")]
public class Derived1: Base1
{
}

public class Base2
{
}

[JsonDiscriminator("Derived")]
public class Derived2: Base2
{
]
````

**Comment by mcatanzariti** [comment]
Hi @NikiforovAll,

Your use case is not intrinsically supported.
BUT by implementing your own version of IDiscriminatorConvention, you should be able to achieve what you want. 

You could have a single implementation of IDiscriminatorConvention that would accept a specific base class in its constructor and you could use this base class to accept or reject a specific type in your TryRegisterType implementation.

Then you could register this discriminator once for "Base1" class and one for "Base2" class.

Let me know if you need more details

**Comment by NikiforovAll** [comment]
Hi @mcatanzariti,
I think I've got the idea. Thank you for the explanation.
