### ISSUE TITLE
error NU1101: Unable to find package Dahomey.Json.Attributes.

### ISSUE THREAD

**Issue by m-abs** [dahomey-technologies/Dahomey.Json#99]
Hi,

Thank you for the quick resolution of my previous issue. 

Unfortunately I cannot install `1.12.0` from nuget.org due to a missing dependency `Dahomey.Json.Attributes`.

**Comment by mcatanzariti** [comment]
Oh right !

I was thinking about packaging both assemblies in the same nuget package.

But actually, I think it is better to create two seperated nuget packages with a dependency between both

**Comment by mcatanzariti** [comment]
fixed in https://github.com/dahomey-technologies/Dahomey.Json/releases/tag/1.12.1
